version: '3.2'

services:
  freeradius:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: radius-gauth
    container_name: "freeradius"
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    environment:
      #- DB_NAME=radius
      #- DB_HOST=postgres
      #- DB_USER=debug
      #- DB_PASS=debug
      #- DB_PORT=5432
      - API_HOST=django
      - API_PORT=8000
      - API_PROTOCOL=http
      - API_TOKEN=djangofreeradiusapitoken
      - RADIUS_SSL_MODE=disable
      - RADIUS_KEY=testing123
      - RADIUS_CLIENTS=192.168.100.0/24
      - RADIUS_DEBUG=yes
    depends_on:
      - postgres
      - django
    restart: always
    networks:
      - backend

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: 2stacks/django-freeradius
    container_name: "django"
    depends_on:
      - postgres
    volumes:
      - ./django-freeradius/tests:/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=radius
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    ports:
      - "8000:8000"
    networks:
      - backend
    command: /start

  postgres:
    image: postgres:10-alpine
    container_name: "postgres"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./certs/postgres/server.crt:/server.crt
      - ./certs/postgres/server.key:/server.key
      - ./certs/postgres/ca.crt:/ca.crt
    environment:
      - POSTGRES_DB=radius
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
    restart: always
    networks:
      - backend
    command: postgres -c ssl=on -c ssl_key_file=/server.key -c ssl_cert_file=/server.crt

volumes:
  postgres_data: {}

networks:
  backend:
    ipam:
      config:
        - subnet: 10.0.0.0/24
